namespace Burning.DofusProtocol.Enums
{
  public enum AllianceRightsBitEnum
  {
    ALLIANCE_RIGHT_NONE = 0,
    ALLIANCE_RIGHT_BOSS = 1,
    ALLIANCE_RIGHT_MANAGE_PRISMS = 2,
    ALLIANCE_RIGHT_TALK_IN_CHAN = 4,
    ALLIANCE_RIGHT_RECRUIT_GUILDS = 8,
    ALLIANCE_RIGHT_KICK_GUILDS = 16, // 0x00000010
    ALLIANCE_RIGHT_MANAGE_RIGHTS = 32, // 0x00000020
  }
}
