namespace Burning.DofusProtocol.Enums
{
  public enum ChatErrorEnum
  {
    CHAT_ERROR_UNKNOWN,
    CHAT_ERROR_RECEIVER_NOT_FOUND,
    CHAT_ERROR_INTERIOR_MONOLOGUE,
    CHAT_ERROR_NO_GUILD,
    CHAT_ERROR_NO_PARTY,
    CHAT_ERROR_ALLIANCE,
    CHAT_ERROR_INVALID_MAP,
    CHAT_ERROR_NO_PARTY_ARENA,
    CHAT_ERROR_NO_TEAM,
    CHAT_ERROR_MALFORMED_CONTENT,
    CHAT_ERROR_NO_CHANNEL_COMMUNITY,
  }
}
