namespace Burning.DofusProtocol.Enums
{
  public enum DialogTypeEnum
  {
    DIALOG_BOOK,
    DIALOG_DIALOG,
    DIALOG_LOCKABLE,
    DIALOG_PURCHASABLE,
    DIALOG_GUILD_INVITATION,
    DIALOG_GUILD_CREATE,
    DIALOG_GUILD_RENAME,
    DIALOG_MARRIAGE,
    DIALOG_DUNGEON_MEETING,
    DIALOG_SPELL_FORGET,
    DIALOG_TELEPORTER,
    DIALOG_EXCHANGE,
    DIALOG_ALLIANCE_INVITATION,
    DIALOG_ALLIANCE_CREATE,
    DIALOG_ALLIANCE_RENAME,
    DIALOG_HAVENBAG_MEETING,
  }
}
