namespace Burning.DofusProtocol.Enums
{
  public enum ExchangeErrorEnum
  {
    REQUEST_IMPOSSIBLE = 1,
    REQUEST_CHARACTER_OCCUPIED = 2,
    REQUEST_CHARACTER_JOB_NOT_EQUIPED = 3,
    REQUEST_CHARACTER_TOOL_TOO_FAR = 4,
    REQUEST_CHARACTER_OVERLOADED = 5,
    REQUEST_CHARACTER_NOT_SUSCRIBER = 6,
    REQUEST_CHARACTER_RESTRICTED = 7,
    REQUEST_CHARACTER_GUEST = 8,
    MOUNT_PADDOCK_ERROR = 10, // 0x0000000A
    BID_SEARCH_ERROR = 11, // 0x0000000B
    SELL_ERROR = 63, // 0x0000003F
    BUY_ERROR = 64, // 0x00000040
  }
}
