namespace Burning.DofusProtocol.Enums
{
  public enum PrismStateEnum
  {
    PRISM_STATE_INVULNERABLE,
    PRISM_STATE_NORMAL,
    PRISM_STATE_ATTACKED,
    PRISM_STATE_FIGHTING,
    PRISM_STATE_WEAKENED,
    PRISM_STATE_VULNERABLE,
    PRISM_STATE_DEFEATED,
    PRISM_STATE_SABOTAGED,
  }
}
