namespace Burning.DofusProtocol.Enums
{
  public enum ServerConnectionErrorEnum
  {
    SERVER_CONNECTION_ERROR_DUE_TO_STATUS,
    SERVER_CONNECTION_ERROR_NO_REASON,
    SERVER_CONNECTION_ERROR_ACCOUNT_RESTRICTED,
    SERVER_CONNECTION_ERROR_COMMUNITY_RESTRICTED,
    SERVER_CONNECTION_ERROR_LOCATION_RESTRICTED,
    SERVER_CONNECTION_ERROR_SUBSCRIBERS_ONLY,
    SERVER_CONNECTION_ERROR_REGULAR_PLAYERS_ONLY,
    SERVER_CONNECTION_ERROR_MONOACCOUNT_CANNOT_VERIFY,
    SERVER_CONNECTION_ERROR_MONOACCOUNT_ONLY,
  }
}
