namespace Burning.DofusProtocol.Enums
{
  public enum SubEntityBindingPointCategoryEnum
  {
    HOOK_POINT_CATEGORY_UNUSED,
    HOOK_POINT_CATEGORY_PET,
    HOOK_POINT_CATEGORY_MOUNT_DRIVER,
    HOOK_POINT_CATEGORY_LIFTED_ENTITY,
    HOOK_POINT_CATEGORY_BASE_BACKGROUND,
    HOOK_POINT_CATEGORY_MERCHANT_BAG,
    HOOK_POINT_CATEGORY_BASE_FOREGROUND,
    HOOK_POINT_CATEGORY_PET_FOLLOWER,
    HOOK_POINT_CATEGORY_UNDERWATER_BUBBLES,
  }
}
