namespace Burning.DofusProtocol.Enums
{
  public enum TaxCollectorErrorReasonEnum
  {
    TAX_COLLECTOR_ERROR_UNKNOWN,
    TAX_COLLECTOR_NOT_FOUND,
    TAX_COLLECTOR_NOT_OWNED,
    TAX_COLLECTOR_NO_RIGHTS,
    TAX_COLLECTOR_MAX_REACHED,
    TAX_COLLECTOR_ALREADY_ONE,
    TAX_COLLECTOR_CANT_HIRE_YET,
    TAX_COLLECTOR_CANT_HIRE_HERE,
    TAX_COLLECTOR_NOT_ENOUGH_KAMAS,
  }
}
