namespace Burning.DofusProtocol.Enums
{
  public enum TreasureHuntRequestEnum
  {
    TREASURE_HUNT_ERROR_UNDEFINED,
    TREASURE_HUNT_OK,
    TREASURE_HUNT_ERROR_NO_QUEST_FOUND,
    TREASURE_HUNT_ERROR_ALREADY_HAVE_QUEST,
    TREASURE_HUNT_ERROR_NOT_AVAILABLE,
    TREASURE_HUNT_ERROR_DAILY_LIMIT_EXCEEDED,
  }
}
