namespace Burning.DofusProtocol.Enums
{
  public enum TreasureHuntFlagRequestEnum
  {
    TREASURE_HUNT_FLAG_ERROR_UNDEFINED,
    TREASURE_HUNT_FLAG_OK,
    TREASURE_HUNT_FLAG_WRONG,
    TREASURE_HUNT_FLAG_TOO_MANY,
    TREASURE_HUNT_FLAG_ERROR_IMPOSSIBLE,
    TREASURE_HUNT_FLAG_WRONG_INDEX,
    TREASURE_HUNT_FLAG_SAME_MAP,
  }
}
