namespace Burning.DofusProtocol.Enums
{
  public enum TreasureHuntDigRequestEnum
  {
    TREASURE_HUNT_DIG_ERROR_UNDEFINED,
    TREASURE_HUNT_DIG_NEW_HINT,
    TREASURE_HUNT_DIG_FINISHED,
    TREASURE_HUNT_DIG_WRONG,
    TREASURE_HUNT_DIG_LOST,
    TREASURE_HUNT_DIG_ERROR_IMPOSSIBLE,
    TREASURE_HUNT_DIG_WRONG_AND_YOU_KNOW_IT,
  }
}
